// Ratings Seeds

const { Ratings } = require('../models');

const ratingData = [
  {"user_id": 1, "album_id": 5, "rating": 3},
  {"user_id": 2, "album_id": 18, "rating": 4},
  {"user_id": 3, "album_id": 12, "rating": 2},
  {"user_id": 4, "album_id": 8, "rating": 5},
  {"user_id": 5, "album_id": 23, "rating": 1},
  {"user_id": 1, "album_id": 15, "rating": 4},
  {"user_id": 2, "album_id": 9, "rating": 3},
  {"user_id": 3, "album_id": 20, "rating": 5},
  {"user_id": 4, "album_id": 6, "rating": 2},
  {"user_id": 5, "album_id": 13, "rating": 1},
  {"user_id": 1, "album_id": 7, "rating": 5},
  {"user_id": 2, "album_id": 25, "rating": 3},
  {"user_id": 3, "album_id": 2, "rating": 4},
  {"user_id": 4, "album_id": 16, "rating": 1},
  {"user_id": 5, "album_id": 10, "rating": 2},
  {"user_id": 1, "album_id": 21, "rating": 3},
  {"user_id": 2, "album_id": 3, "rating": 4},
  {"user_id": 3, "album_id": 19, "rating": 5},
  {"user_id": 4, "album_id": 14, "rating": 1},
  {"user_id": 5, "album_id": 17, "rating": 2},
  {"user_id": 1, "album_id": 22, "rating": 3},
  {"user_id": 2, "album_id": 11, "rating": 4},
  {"user_id": 3, "album_id": 4, "rating": 5},
  {"user_id": 4, "album_id": 1, "rating": 1},
  {"user_id": 5, "album_id": 24, "rating": 2},
  {"user_id": 1, "album_id": 25, "rating": 3},
  {"user_id": 2, "album_id": 5, "rating": 4},
  {"user_id": 3, "album_id": 18, "rating": 5},
  {"user_id": 4, "album_id": 12, "rating": 1},
  {"user_id": 5, "album_id": 8, "rating": 2},
  {"user_id": 1, "album_id": 13, "rating": 3},
  {"user_id": 2, "album_id": 7, "rating": 4},
  {"user_id": 3, "album_id": 25, "rating": 5},
  {"user_id": 4, "album_id": 2, "rating": 1},
  {"user_id": 5, "album_id": 16, "rating": 2},
  {"user_id": 1, "album_id": 10, "rating": 3},
  {"user_id": 2, "album_id": 21, "rating": 4},
  {"user_id": 3, "album_id": 3, "rating": 5},
  {"user_id": 4, "album_id": 19, "rating": 1},
  {"user_id": 5, "album_id": 14, "rating": 2},
  {"user_id": 1, "album_id": 17, "rating": 3},
  {"user_id": 2, "album_id": 22, "rating": 4},
  {"user_id": 3, "album_id": 11, "rating": 5},
  {"user_id": 4, "album_id": 4, "rating": 1},
  {"user_id": 5, "album_id": 1, "rating": 2},
  {"user_id": 1, "album_id": 6, "rating": 3},
  {"user_id": 2, "album_id": 23, "rating": 4},
  {"user_id": 3, "album_id": 5, "rating": 5},
  {"user_id": 4, "album_id": 18, "rating": 1},
  {"user_id": 5, "album_id": 12, "rating": 2},
  {"user_id": 1, "album_id": 13, "rating": 3},
  {"user_id": 2, "album_id": 7, "rating": 4},
  {"user_id": 3, "album_id": 25, "rating": 5},
  {"user_id": 4, "album_id": 2, "rating": 1},
  {"user_id": 5, "album_id": 16, "rating": 2},
  {"user_id": 1, "album_id": 10, "rating": 3},
  {"user_id": 2, "album_id": 21, "rating": 4},
  {"user_id": 3, "album_id": 3, "rating": 5},
  {"user_id": 4, "album_id": 19, "rating": 1},
  {"user_id": 5, "album_id": 14, "rating": 2}
]

const seedRatings = () => Ratings.bulkCreate(ratingData);

module.exports = seedRatings;